class Autogenerated {
  List<Instrucciones> instrucciones = [];
  int norteGrado = 0;

  Autogenerated({required this.instrucciones, required this.norteGrado});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['instrucciones'] != null) {
      instrucciones = <Instrucciones>[];
      json['instrucciones'].forEach((v) {
        instrucciones.add(new Instrucciones.fromJson(v));
      });
    }
    if (json['norteGrado'] != null) {
      norteGrado = json['norteGrado'];
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.instrucciones != null) {
      data['instrucciones'] =
          this.instrucciones.map((v) => v.toJson()).toList();
    }

    if (this.norteGrado != null) {
      data['norteGrado'] = this.norteGrado;
    }
    return data;
  }
}

class Instrucciones {
  String? commando;
  String? siguienteNodo;
  int? distancia;
  bool? existePuerta;
  String? sentidoOrigen;
  String? sentidoDestino;

  Instrucciones(
      {this.commando,
        this.siguienteNodo,
        this.distancia,
        this.existePuerta,
        this.sentidoOrigen,
        this.sentidoDestino});

  String instruccionToString(){
    String retorna="";
    if(this.commando!=""){
      retorna = this.commando!;
    }else{
      if(this.distancia! > 0){
        retorna = "Tiene que avanzar " + this.distancia.toString() + " metros.";
        retorna += " El siguiente nodo es: " + this.siguienteNodo! + ".";
        if(this.existePuerta == true){
          retorna += "Hay una puerta en el camino.";
        }
      }
    }
    return retorna;
  }

  Instrucciones.fromJson(Map<String, dynamic> json) {
    commando = json['commando'];
    siguienteNodo = json['siguienteNodo'];
    distancia = json['distancia'];
    existePuerta = json['existePuerta'];
    sentidoOrigen = json['sentidoOrigen'];
    sentidoDestino = json['sentidoDestino'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['commando'] = this.commando;
    data['siguienteNodo'] = this.siguienteNodo;
    data['distancia'] = this.distancia;
    data['existePuerta'] = this.existePuerta;
    data['sentidoOrigen'] = this.sentidoOrigen;
    data['sentidoDestino'] = this.sentidoDestino;
    return data;
  }
}