// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd50NZw7_BHqCt0DHAVne7xOK-sWSmiWY',
    appId: '1:532814462924:web:cb1ffeab2b16eed22be769',
    messagingSenderId: '532814462924',
    projectId: 'guio-54def',
    authDomain: 'guio-54def.firebaseapp.com',
    storageBucket: 'guio-54def.appspot.com',
    measurementId: 'G-D0Q4CEQFH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8mVlv43LTT0jlo3XaKd63F3NWkVONnM',
    appId: '1:532814462924:android:7f00fb3c1b53abc92be769',
    messagingSenderId: '532814462924',
    projectId: 'guio-54def',
    storageBucket: 'guio-54def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHE29hKamGxkKvFvlC9zvBm0fIC899cA',
    appId: '1:532814462924:ios:59013f657509821d2be769',
    messagingSenderId: '532814462924',
    projectId: 'guio-54def',
    storageBucket: 'guio-54def.appspot.com',
    iosClientId: '532814462924-h3m84hukokmr4646pc7q0naeug537p40.apps.googleusercontent.com',
    iosBundleId: 'com.example.guioProyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHE29hKamGxkKvFvlC9zvBm0fIC899cA',
    appId: '1:532814462924:ios:59013f657509821d2be769',
    messagingSenderId: '532814462924',
    projectId: 'guio-54def',
    storageBucket: 'guio-54def.appspot.com',
    iosClientId: '532814462924-h3m84hukokmr4646pc7q0naeug537p40.apps.googleusercontent.com',
    iosBundleId: 'com.example.guioProyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd50NZw7_BHqCt0DHAVne7xOK-sWSmiWY',
    appId: '1:532814462924:web:68807b93e02414232be769',
    messagingSenderId: '532814462924',
    projectId: 'guio-54def',
    authDomain: 'guio-54def.firebaseapp.com',
    storageBucket: 'guio-54def.appspot.com',
    measurementId: 'G-TJY6H5N4Q6',
  );
}
